uploads = []
outputs = []

[[generated]]
id = "Yj8UIlR_qCvTFbEEqV_ul"
uri = "file://artifacts/printkingdriver/public/assets/img/cat-advanced-new.png"
type = "image"
title = "advanced systems firmware shield"
